-- 1. PATCHES (The version of the game)
CREATE TABLE patches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT NOT NULL, -- e.g. "2.0"
    name TEXT NOT NULL,    -- e.g. "A Realm Reborn"
    release_date DATE
);

-- 2. CURRENCIES (Gils, MGP, etc.)
CREATE TABLE currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,    -- e.g. "MGP"
    icon_url TEXT          -- URL to the currency icon
);

-- 3. SOURCES (Where to get it)
CREATE TABLE sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,    -- e.g. "Gold Saucer"
    type TEXT              -- e.g. "Vendor", "Raid", "Dungeon"
);

-- 4. MASCOTS (The main entity)
CREATE TABLE mascots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    
    -- LINK: A mascot belongs to ONE patch
    patch_id BIGINT REFERENCES patches(id), 
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. ACQUISITIONS (The connection between Mascot, Source, and Price)
CREATE TABLE mascot_acquisitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- LINKS
    mascot_id BIGINT REFERENCES mascots(id) ON DELETE CASCADE,
    source_id BIGINT REFERENCES sources(id) ON DELETE CASCADE,
    currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL, -- Nullable because some things are free/drops
    
    cost INTEGER,          -- e.g. 10000
    details TEXT           -- e.g. "Drop rate 10%"
);

-- Enable RLS (Security) on all tables
ALTER TABLE patches ENABLE ROW LEVEL SECURITY;
ALTER TABLE currencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE mascots ENABLE ROW LEVEL SECURITY;
ALTER TABLE mascot_acquisitions ENABLE ROW LEVEL SECURITY;

-- Allow Public Read Access (Everyone can see the collection details)
CREATE POLICY "Public Read Patches" ON patches FOR SELECT USING (true);
CREATE POLICY "Public Read Currencies" ON currencies FOR SELECT USING (true);
CREATE POLICY "Public Read Sources" ON sources FOR SELECT USING (true);
CREATE POLICY "Public Read Mascots" ON mascots FOR SELECT USING (true);
CREATE POLICY "Public Read Acquisitions" ON mascot_acquisitions FOR SELECT USING (true);

-- DUMMY DATA INSERTION (To test)
-- 1. Patch
INSERT INTO patches (version, name) VALUES ('2.0', 'A Realm Reborn');

-- 2. Currency
INSERT INTO currencies (name, icon_url) VALUES ('MGP', 'https://example.com/mgp.png');

-- 3. Source
INSERT INTO sources (name, type) VALUES ('Gold Saucer', 'Vendor');

-- 4. Mascot
INSERT INTO mascots (name, patch_id, image_url) 
VALUES ('Fat Cat', 1, 'https://img.finalfantasyxiv.com/lds/promo/h/r/5s_g7M8-x_o4u0a9j_3qjq_j.png');

-- 5. Link them! (Fat Cat costs 10k MGP at Gold Saucer)
INSERT INTO mascot_acquisitions (mascot_id, source_id, currency_id, cost)
VALUES (1, 1, 1, 10000);
