-- FIX: Ensure characters table exists and has correct permissions

-- 1. Create table if not exists
CREATE TABLE IF NOT EXISTS public.characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL UNIQUE,
    character_id INT NOT NULL, -- FFXIV Character ID
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS (Security)
ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;

-- 3. Add Policy for SELECT (Reading)
-- This is likely what is missing if you inserted data but can't read it
DROP POLICY IF EXISTS "Users can view own character" ON public.characters;
CREATE POLICY "Users can view own character"
ON public.characters FOR SELECT
USING (auth.uid() = user_id);

-- 4. Add Policy for INSERT/UPDATE (Just in case you want to allow it later from UI)
DROP POLICY IF EXISTS "Users can link own character" ON public.characters;
CREATE POLICY "Users can link own character"
ON public.characters FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own character" ON public.characters;
CREATE POLICY "Users can update own character"
ON public.characters FOR UPDATE
USING (auth.uid() = user_id);
