-- Create the table
CREATE TABLE mascots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert dummy data
INSERT INTO mascots (name, description, image_url) VALUES
('Fat Cat', 'A gluttonous feline that eats everything in sight.', 'https://img.finalfantasyxiv.com/lds/promo/h/r/5s_g7M8-x_o4u0a9j_3qjq_j.png'),
('Namazu', 'Yes, yes. Very slippery.', 'https://img.finalfantasyxiv.com/lds/promo/h/e/8s_j7M9-x_o4u0a9j_3qjq_j.png'),
('Paissa Brat', 'Has a very punchable face.', 'https://img.finalfantasyxiv.com/lds/promo/h/p/2s_k7M6-x_o4u0a9j_3qjq_j.png');

-- Enable Row Level Security (RLS)
ALTER TABLE mascots ENABLE ROW LEVEL SECURITY;

-- Create a Policy to allow public read access
CREATE POLICY "Enable read access for all users" ON mascots
FOR SELECT USING (true);
